# -*- coding: utf-8 -*-
"""VIDEO TO IMG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mDA0cvMkaSswrYgLK_4N36HdqD0erwD5
"""

!pip install ultralytics
from ultralytics import YOLO
import cv2
import os

!pip install opencv-python

# Importing all necessary librariesiimport cv2
import os
from google.colab import drive
drive.mount('/content/drive')

# Read the video from specified path
cam = cv2.VideoCapture("/content/drive/MyDrive/06-03-2024 04_59_59 (UTC+05_30).mkv")
try:

    # creating a folder named data
    if not os.path.exists('some road pic'):
        os.makedirs('some road pic')

# if not created then raise error
except OSError:
    print ('Error: Creating directory of data')

# frame
currentframe = 0

while(True):

    # reading from frame
    ret,frame = cam.read()

    if ret:
        # if video is still left continue creating images
        name = './some road pic/SecondHoghlyBridge_200_' + str(currentframe) + '.jpg'
        print ('Creating...' + name)

        # writing the extracted images
        cv2.imwrite(name, frame)

        # increasing counter so that it will
        # show how many frames are created
        currentframe += 1
    else:
        break



# Release all space and windows once done
cam.release()
cv2.destroyAllWindows()

import shutil
from google.colab import drive
drive.mount('/content/drive')
shutil.copytree("/content/some road pic", "/content/drive/MyDrive/FRAMES/all")